name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
           - uses: actions/checkout@v3
           - run: make test
           - run: make lint
           - run: make setup
           - run: make start
           - run: ls -la
